server {
    listen 80;
    listen [::]:80;

    server_name veltrixo.test;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name veltrixo.test *.veltrixo.test;

    ssl_certificate     /etc/nginx/ssl/veltrixo.test.crt;
    ssl_certificate_key /etc/nginx/ssl/veltrixo.test.key;

    root /var/www/Veltrixo/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTPS $https;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
    }

    location ~ /\.ht {
        deny all;
    }
}
